spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:admintools}?sslmode=require
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: ${TZ:America/Bogota}

logging:
  level:
    com.admintools: DEBUG
    org.hibernate.SQL: DEBUG
