spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/admintools}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: ${TZ:America/Bogota}

telegram:
  errors-chat-id: "-1004462749433"

logging:
  level:
    com.admintools: DEBUG
